### ISSUE TITLE
UDW integration compilation error

### ISSUE THREAD

**Issue by delebash** [GDi4K/unreal-openland#58]
OpenLand 2.2.0
UE5 Preview 2

When adding the OpenLand_UDW_Support function to the landscape material you get a compilation error.

![UnrealEditor_RXHgc9xujA](https://user-images.githubusercontent.com/2220160/160448055-528d625d-7a4d-4fcd-80e4-a9ef2db8a60c.png)
.

**Comment by arunoda** [comment]
Fixed with https://github.com/GDi4K/unreal-openland/releases/tag/2.20.1
